/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package basdatbab13.CRUDFolder.Nilai;

import basdatbab13.CRUDFolder.mahasiswa.*;
import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author Hype GLK
 */
public class NilaiPanel extends javax.swing.JPanel {

    /**
     * Creates new form MahasiswaPanel
     */
    public NilaiPanel() {
        initComponents();
        cl = (CardLayout) crudPanel.getLayout();
        setInsert();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudPanel = new javax.swing.JPanel();
        insertPanel = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        insertCourseCode1 = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        genderComboBox1 = new javax.swing.JComboBox<>();
        updatePanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        courseComboBox = new javax.swing.JComboBox<>();
        courseNameField = new javax.swing.JTextField();
        courseComboBox2 = new javax.swing.JComboBox<>();
        removePanel = new javax.swing.JPanel();
        updateButton1 = new javax.swing.JButton();
        courseComboBox1 = new javax.swing.JComboBox<>();
        courseNameField1 = new javax.swing.JTextField();
        courseCodeField1 = new javax.swing.JTextField();
        updatePanel1 = new javax.swing.JPanel();
        updateButton2 = new javax.swing.JButton();
        courseComboBox3 = new javax.swing.JComboBox<>();
        courseNameField2 = new javax.swing.JTextField();
        courseComboBox4 = new javax.swing.JComboBox<>();
        toUpdatePanelButton = new javax.swing.JButton();
        toInsertPanelButton = new javax.swing.JButton();
        toRemovePanelButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(625, 600));
        setMinimumSize(new java.awt.Dimension(625, 600));
        setPreferredSize(new java.awt.Dimension(625, 600));

        crudPanel.setLayout(new java.awt.CardLayout());

        insertPanel.setBackground(new java.awt.Color(51, 51, 51));

        insertButton.setText("Insert Takes");

        insertCourseCode1.setText("Nilai");
        insertCourseCode1.setPreferredSize(new java.awt.Dimension(180, 22));
        insertCourseCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCourseCode1ActionPerformed(evt);
            }
        });

        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        genderComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertPanelLayout = new javax.swing.GroupLayout(insertPanel);
        insertPanel.setLayout(insertPanelLayout);
        insertPanelLayout.setHorizontalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addComponent(genderComboBox1, 0, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(insertCourseCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        insertPanelLayout.setVerticalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertCourseCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        crudPanel.add(insertPanel, "insertCard");

        updatePanel.setBackground(new java.awt.Color(51, 51, 51));
        updatePanel.setPreferredSize(new java.awt.Dimension(607, 66));

        updateButton.setText("Update Takes");

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox.setPreferredSize(new java.awt.Dimension(72, 30));

        courseComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox2.setPreferredSize(new java.awt.Dimension(72, 30));

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(courseComboBox, 0, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        crudPanel.add(updatePanel, "updateCard");

        removePanel.setBackground(new java.awt.Color(51, 51, 51));
        removePanel.setPreferredSize(new java.awt.Dimension(607, 66));

        updateButton1.setText("Remove Student");

        courseComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox1.setPreferredSize(new java.awt.Dimension(72, 30));

        updatePanel1.setBackground(new java.awt.Color(51, 51, 51));
        updatePanel1.setPreferredSize(new java.awt.Dimension(607, 66));

        updateButton2.setText("Remove Takes");

        courseComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox3.setPreferredSize(new java.awt.Dimension(72, 30));

        courseComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox4.setPreferredSize(new java.awt.Dimension(72, 30));

        javax.swing.GroupLayout updatePanel1Layout = new javax.swing.GroupLayout(updatePanel1);
        updatePanel1.setLayout(updatePanel1Layout);
        updatePanel1Layout.setHorizontalGroup(
            updatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanel1Layout.createSequentialGroup()
                .addComponent(courseComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseNameField2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(updateButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updatePanel1Layout.setVerticalGroup(
            updatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanel1Layout.createSequentialGroup()
                .addGroup(updatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout removePanelLayout = new javax.swing.GroupLayout(removePanel);
        removePanel.setLayout(removePanelLayout);
        removePanelLayout.setHorizontalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addComponent(courseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseCodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(courseNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(updateButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(removePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(updatePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        removePanelLayout.setVerticalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseCodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(removePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(updatePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        crudPanel.add(removePanel, "removeCard");

        toUpdatePanelButton.setText("Update Data");
        toUpdatePanelButton.setPreferredSize(new java.awt.Dimension(180, 30));
        toUpdatePanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toUpdatePanelButtonActionPerformed(evt);
            }
        });

        toInsertPanelButton.setBackground(new java.awt.Color(51, 51, 51));
        toInsertPanelButton.setText("Insert Data");
        toInsertPanelButton.setPreferredSize(new java.awt.Dimension(180, 30));
        toInsertPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toInsertPanelButtonActionPerformed(evt);
            }
        });

        toRemovePanelButton.setText("Remove Data");
        toRemovePanelButton.setPreferredSize(new java.awt.Dimension(180, 30));
        toRemovePanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRemovePanelButtonActionPerformed(evt);
            }
        });

        courseTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Mahasiswa", "Mata Kuliah", "Nilai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        courseTable.setEnabled(false);
        courseTable.setGridColor(new java.awt.Color(153, 153, 153));
        courseTable.setPreferredSize(new java.awt.Dimension(150, 607));
        courseTable.setSelectionForeground(new java.awt.Color(153, 153, 153));
        courseTable.setShowGrid(true);
        scrollPanel.setViewportView(courseTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(crudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toInsertPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toUpdatePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toRemovePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPanel))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toInsertPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toUpdatePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toRemovePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toUpdatePanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toUpdatePanelButtonActionPerformed
        // TODO add your handling code here:
        setUpdate();
    }//GEN-LAST:event_toUpdatePanelButtonActionPerformed

    private void toInsertPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toInsertPanelButtonActionPerformed
        // TODO add your handling code here:
        setInsert();
    }//GEN-LAST:event_toInsertPanelButtonActionPerformed

    private void toRemovePanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRemovePanelButtonActionPerformed
        // TODO add your handling code here:
        setRemove();
    }//GEN-LAST:event_toRemovePanelButtonActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void insertCourseCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCourseCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertCourseCode1ActionPerformed

    private void genderComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBox1ActionPerformed

    void setInsert(){
       toInsertPanelButton.setBackground(new Color(51,51,51));
       if(previousButton!=null)
       previousButton.setBackground(new Color(78,80,82));
       cl.show(crudPanel, "insertCard");
       previousButton=toInsertPanelButton;
       revalidate();
       repaint();
    }
    void setUpdate(){
       toUpdatePanelButton.setBackground(new Color(51,51,51));
       if(previousButton!=null)
       previousButton.setBackground(new Color(78,80,82));
       cl.show(crudPanel, "updateCard");
       previousButton=toUpdatePanelButton;
       revalidate();
       repaint();
    }
    
    void setRemove(){
        toRemovePanelButton.setBackground(new Color(51,51,51));
       if(previousButton!=null)
        previousButton.setBackground(new Color(78,80,82));
       cl.show(crudPanel, "removeCard");
       previousButton=toRemovePanelButton;
       revalidate();
       repaint();
    }
    private javax.swing.JButton previousButton; 
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseCodeField1;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JComboBox<String> courseComboBox1;
    private javax.swing.JComboBox<String> courseComboBox2;
    private javax.swing.JComboBox<String> courseComboBox3;
    private javax.swing.JComboBox<String> courseComboBox4;
    private javax.swing.JTextField courseNameField;
    private javax.swing.JTextField courseNameField1;
    private javax.swing.JTextField courseNameField2;
    private javax.swing.JTable courseTable;
    private javax.swing.JPanel crudPanel;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JComboBox<String> genderComboBox1;
    private javax.swing.JButton insertButton;
    private javax.swing.JTextField insertCourseCode1;
    private javax.swing.JPanel insertPanel;
    private javax.swing.JPanel removePanel;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton toInsertPanelButton;
    private javax.swing.JButton toRemovePanelButton;
    private javax.swing.JButton toUpdatePanelButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateButton1;
    private javax.swing.JButton updateButton2;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JPanel updatePanel1;
    // End of variables declaration//GEN-END:variables
}
