/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basdatbab13;
import basdatbab13.CRUDFolder.mahasiswa.MahasiswaPanel;
import basdatbab13.CRUDFolder.Nilai.NilaiPanel;
import basdatbab13.CRUDFolder.MataKuliah.CourseCRUD;
import java.awt.CardLayout;
import java.awt.Color;
import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.*;
/**
 *
 * @author Hype GLK
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        kiri = (CardLayout) PanelKiri.getLayout();
        kanan = (CardLayout) PanelKanan.getLayout();
        kiri.show(PanelKiri,"home");
        setConnect();
    }
    
    void setCourse(){
        PanelKanan.add(new CourseCRUD(getConnection()),"course");
        kanan.show(PanelKanan, "course");
        PanelKanan.revalidate();
        PanelKanan.repaint();
        coursePanelButton.setBackground(new Color(0,17,17));
        if(previousButton!=null)
        previousButton.setBackground(new Color(0,51,51));
        previousButton = coursePanelButton;
        PanelKiri.repaint();
        PanelKiri.revalidate();
    }
    
    void setStudent(){
        PanelKanan.add(new MahasiswaPanel(getConnection()),"student");
        kanan.show(PanelKanan, "student");
        PanelKanan.revalidate();
        PanelKanan.repaint();
        studentButton.setBackground(new Color(0,17,17));
        if(previousButton!=null)
        previousButton.setBackground(new Color(0,51,51));
        previousButton = studentButton;
        PanelKiri.repaint();
        PanelKiri.revalidate();
    }
    
    void setTakes(){
        PanelKanan.add(new NilaiPanel(getConnection()),"takes");
        kanan.show(PanelKanan, "takes");
        PanelKanan.revalidate();
        PanelKanan.repaint();
        takesButton.setBackground(new Color(0,17,17));
        if(previousButton!=null)
        previousButton.setBackground(new Color(0,51,51));
        previousButton = takesButton;
        PanelKiri.repaint();
        PanelKiri.revalidate();
        
    }
    
    void setConnect(){
        kanan.show(PanelKanan,"connect");
        PanelKanan.repaint();
        PanelKanan.revalidate();
        connectPage.setBackground(new Color(0,17,17));
        infoPage.setBackground(new Color(0,51,51));
        PanelKiri.repaint();
        PanelKiri.revalidate();
    }
    void setDesc(){
        kanan.show(PanelKanan,"desc");
        PanelKanan.repaint();
        PanelKanan.revalidate();
        infoPage.setBackground(new Color(0,17,17));
        connectPage.setBackground(new Color(0,51,51));
        PanelKiri.repaint();
        PanelKiri.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelKiri = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        coursePanelButton = new javax.swing.JButton();
        disconnectButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        takesButton = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        infoPage = new javax.swing.JButton();
        connectPage = new javax.swing.JButton();
        PanelKanan = new javax.swing.JPanel();
        connectPanelLogin = new javax.swing.JPanel();
        labelConnect = new javax.swing.JLabel();
        loginFieldPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        connectDBButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        descPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        PanelKiri.setBackground(new java.awt.Color(153, 153, 153));
        PanelKiri.setPreferredSize(new java.awt.Dimension(256, 600));
        PanelKiri.setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(153, 153, 153));

        coursePanelButton.setBackground(new java.awt.Color(0, 51, 51));
        coursePanelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coursePanelButton.setText("Course");
        coursePanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursePanelButtonActionPerformed(evt);
            }
        });

        disconnectButton.setBackground(new java.awt.Color(51, 0, 0));
        disconnectButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        disconnectButton.setForeground(new java.awt.Color(255, 153, 153));
        disconnectButton.setText("Disconnect");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed( evt);
            }
        });

        studentButton.setBackground(new java.awt.Color(0, 51, 51));
        studentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentButton.setText("Student");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });

        takesButton.setBackground(new java.awt.Color(0, 51, 51));
        takesButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        takesButton.setText("Takes");
        takesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coursePanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(disconnectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(studentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(takesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coursePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(takesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(disconnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        PanelKiri.add(menuPanel, "menu");

        homePanel.setBackground(new java.awt.Color(153, 153, 153));

        infoPage.setBackground(new java.awt.Color(0, 51, 51));
        infoPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        infoPage.setText("Database Info");
        infoPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoPageActionPerformed(evt);
            }
        });

        connectPage.setBackground(new java.awt.Color(0, 17, 17));
        connectPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        connectPage.setText("Connect To Database");
        connectPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectPage, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(infoPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(connectPage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        PanelKiri.add(homePanel, "home");

        PanelKanan.setBackground(new java.awt.Color(51, 51, 51));
        PanelKanan.setMinimumSize(new java.awt.Dimension(625, 600));
        PanelKanan.setLayout(new java.awt.CardLayout());

        connectPanelLogin.setBackground(new java.awt.Color(51, 51, 51));

        labelConnect.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelConnect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConnect.setText("Connect To Database");

        loginFieldPanel.setBackground(new java.awt.Color(51, 51, 51));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usernameLabel.setText("Username: ");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordLabel.setText("Password: ");

        usernameField.setBackground(new java.awt.Color(51, 51, 51));

        connectDBButton.setBackground(new java.awt.Color(0, 51, 51));
        connectDBButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        connectDBButton.setText("Connect Database");
        connectDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectDBButtonActionPerformed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(51, 51, 51));
        passwordField.setText("jPasswordField1");
        passwordField.setPreferredSize(new java.awt.Dimension(68, 26));

        javax.swing.GroupLayout loginFieldPanelLayout = new javax.swing.GroupLayout(loginFieldPanel);
        loginFieldPanel.setLayout(loginFieldPanelLayout);
        loginFieldPanelLayout.setHorizontalGroup(
            loginFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameField)
            .addGroup(loginFieldPanelLayout.createSequentialGroup()
                .addGroup(loginFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(passwordLabel))
                .addGap(0, 378, Short.MAX_VALUE))
            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFieldPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(connectDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        loginFieldPanelLayout.setVerticalGroup(
            loginFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFieldPanelLayout.createSequentialGroup()
                .addComponent(usernameLabel)
                .addGap(25, 25, 25)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addGap(25, 25, 25)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(connectDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout connectPanelLoginLayout = new javax.swing.GroupLayout(connectPanelLogin);
        connectPanelLogin.setLayout(connectPanelLoginLayout);
        connectPanelLoginLayout.setHorizontalGroup(
            connectPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connectPanelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        connectPanelLoginLayout.setVerticalGroup(
            connectPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectPanelLoginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labelConnect)
                .addGap(27, 27, 27)
                .addComponent(loginFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        PanelKanan.add(connectPanelLogin, "connect");

        jLabel5.setText("Deskripsi");

        javax.swing.GroupLayout descPanelLayout = new javax.swing.GroupLayout(descPanel);
        descPanel.setLayout(descPanelLayout);
        descPanelLayout.setHorizontalGroup(
            descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descPanelLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel5)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        descPanelLayout.setVerticalGroup(
            descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel5)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        PanelKanan.add(descPanel, "desc");

        Header.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Student Management");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(PanelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelKiri, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(PanelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoPageActionPerformed
        // TODO add your handling code here:
        setDesc();
    }//GEN-LAST:event_infoPageActionPerformed

    private void connectPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectPageActionPerformed
        // TODO add your handling code here:
        setConnect();
    }//GEN-LAST:event_connectPageActionPerformed

    private void connectDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectDBButtonActionPerformed
        // TODO add your handling code here:
        kiri.show(PanelKiri, "menu");
        PanelKiri.repaint();
        PanelKiri.revalidate();
        setCourse();    
    }//GEN-LAST:event_connectDBButtonActionPerformed
    private void coursePanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursePanelButtonActionPerformed
        // TODO add your handling code here:
        setCourse();
    }//GEN-LAST:event_coursePanelButtonActionPerformed

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
        setStudent();
    }//GEN-LAST:event_studentButtonActionPerformed

    private void takesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takesButtonActionPerformed
        // TODO add your handling code here:
        setTakes();
    }//GEN-LAST:event_takesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatDarkLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainFrame().setVisible(true);
            }
        });
    }

    public Connection getConnection(){
        if(conn == null){

                conn = DBConnection.getConnection();
          
        }
        return conn;
    }
    private javax.swing.JButton previousButton;
    private Connection conn;
    CardLayout kiri;
    CardLayout kanan;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel PanelKanan;
    private javax.swing.JPanel PanelKiri;
    private javax.swing.JButton connectDBButton;
    private javax.swing.JButton connectPage;
    private javax.swing.JPanel connectPanelLogin;
    private javax.swing.JButton coursePanelButton;
    private javax.swing.JPanel descPanel;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton infoPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelConnect;
    private javax.swing.JPanel loginFieldPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton takesButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
